import { Container } from "@/components/shared/container";
import { Reveal } from "@/components/shared/reveal";
import { SectionHeading } from "@/components/shared/section-heading";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    question: "Which platforms are supported?",
    answer:
      "Pipflow is built for MetaTrader 4 and MetaTrader 5 Expert Advisors. Any EA can be connected — no changes to your strategy logic required.",
  },
  {
    question: "Do I need to install anything on my VPS?",
    answer:
      "Just a lightweight bridge that runs alongside your EAs. It maintains an encrypted outbound connection to Pipflow, so you never open inbound ports or share VPS credentials.",
  },
  {
    question: "Can Pipflow place trades on my behalf?",
    answer:
      "No. Pipflow controls your EAs — start, pause, stop, and risk parameters. Trade decisions always stay with your strategies, and your funds always stay with your broker.",
  },
  {
    question: "What happens if my EA loses connection?",
    answer:
      "You get an instant connection-lost alert, and server-side guardrails such as daily loss limits remain enforced. When the bridge reconnects, state is synchronized automatically.",
  },
  {
    question: "Is my trading data secure?",
    answer:
      "All traffic is encrypted in transit, commands are signed and audited, and API keys are scoped to the minimum permissions needed. We never ask for your broker password.",
  },
  {
    question: "Is this a live product?",
    answer:
      "This is a product prototype. All trading data you see is generated by a realistic simulation layer — the live MT4/MT5 bridge is on the roadmap.",
  },
] as const;

export function Faq() {
  return (
    <section id="faq" className="scroll-mt-24 py-20 sm:py-28">
      <Container className="max-w-3xl">
        <Reveal>
          <SectionHeading
            eyebrow="FAQ"
            title="Frequently asked questions"
            description="Everything you need to know before putting your bots under command."
          />
        </Reveal>

        <Reveal delay={0.1}>
          <Accordion type="single" collapsible className="mt-12">
            {faqs.map((faq) => (
              <AccordionItem key={faq.question} value={faq.question}>
                <AccordionTrigger className="text-left text-base">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-sm leading-relaxed text-muted-foreground">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </Reveal>
      </Container>
    </section>
  );
}
